package com.mycompany.myapp;

import com.codename1.components.OnOffSwitch;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.CheckBox;
import com.codename1.ui.Container;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.spinner.Picker;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        
        
         
        Form f =  new Form("Form", BoxLayout.y());      
        TextField tfPrenom = new TextField("", "Prenom");
        TextField tfNom = new TextField("", "Nom");
        TextField tfNum =  new TextField("","Numero");
        
        Picker regionPicker = new Picker();
   regionPicker.setStrings("Ariana","Béja", "Ben Arous", "Bizerte", "Gabès", "Gafsa",
             "Jendouba", "Kairouan", "Kasserine", "Kébili", "Kef", "Mahdia", "Manouba", "Médenine",
             "Monastir", "Nabeul", "Sfax", "Sidi Bouzid", "Siliana", "Sousse", "Tataouine", "Tozeur", "Tunis", "Zaghouan");

Picker villePicker = new Picker();

String[]            ArianaVilles = {"Ariana ville", "borj Louzir", "Borj Touil", "Chargia", "Chargia", "Cité El Ghazela", "Ennasr", "Ettadhamen", "Soukra", "Menzah","Raoued"};
String[]            BéjaVilles = {"Amdoun", "Goubellat", "Mjez El Beb", "Nefza", "Tebourzok", "Testour"};
String[]           BenArousVilles = {"Bir El Kassa", "Borj Cedria", "Boumhal", "Boukarnine", "Boukarnine", "El Mourouj", "Ezzahra", "Fouchena", "Hammam Lif", "Morneg", "Rades"};
String[]           BizerteVilles = {"El Alia", "Ghar El Melh", "Mateur", "Menzel Borgiba", "Ras Jebal", "Sejnane", "Zarzouna"};
String[]          GabèsVilles = {"EL Hamma", "El Metouia", "Mareth", "Matmata"};
String[]        GafsaVilles = {"Belkhyr", "El Ksaar", "Metlaoui", "Redeyef"};
String[]         JendoubaVilles ={"Ain Drahem", "Bou Salem", "Fernena", "Ghardimaouu", "Tbarka"};
String[]         KairouanVilles ={"Bou Hajla", "Chebika", "Hafouz", "Ousletia"};
String[]        KasserineVilles = {"Sbeitla", "Thala", "Foussana", "Hassi El Ferid", "Feriana"};
String[]       KébiliVilles = {"Douz", "El Faouar", "Souk El Ahad"};
String[]        KefVilles = {"Dahmani", "Le Sers", "Nebeur", "Tajerouine"};
String[]      MahdiaVilles = {"Bou Merdes", "Chorbane", "El Jem", "Hbira", "Chebba", "Souassi", "Melloulech"};
String[]      ManoubaVilles = {"Douar Hicher", "Oued Ellil", "Borj El Amri", "", "Chebba", "Mornaguia", "Den Den"};
String[]      MonastirVilles = {"Sahline", "Ksar Hellal", "Jemmal", "Moknine", "Zéramdine", "Bembla", "Sayada"};
String[]    MédenineVilles = {"Ben Gardane", "Zarzis", "Djerba Midoun", "Djerba Houmt Souk", "Tataouine", "Remada", "Djerba Ajim"};
String[]    NabeulVilles = {"Hammamet", "Korba", "Kelibia", "Beni Khiar", "Grombalia", "Soliman", "Korbous","Haouaria"};
String[]     SfaxVilles = {"Agareb", "Bir Ali Ben Khalifa", "El Aïn", "Gremda", "Mahres", "Menzel Chaker", "Kerkennah "};
String[]      SidibouzidVilles = {"Bir El Mater", "Mezzouna", "Meknassy", "Menzel Bouzaiane", "Jelma", "Ouled Haffouz", "Sbeitla", "Souk Jedid"};
String[]      SilianaVilles = {"Makthar", "Gaâfour", "Bargou", "Bargou", "Beni Mtir", "Boulhem", "Kesra"};
String[]       SousseVilles = {"Bouficha", "Enfidha", "Hammam Sousse", "Hergla", "Kantaoui-Sousse", "Msaken", "Port El-Kantaoui"};
String[]    TataouineVilles ={"Bir Lahmar", "Douiret", "Dehiba", "Ksar El Ferch", "Smâr", "Remada"};  
String[]       TozeurVilles = {"Degache", "Hamet Jerid", "Metlaoui", "Nefta", "Tamerza"};
String[]     tunisVilles = {"Ben Arous", "Carthage", "El Aouina", "La Marsa", "La Goulette", "La Soukra", "Sidi Bou Said"};
String[]       ZaghouenVilles ={"Bir Mcherga", "Bir Salah", "Bir Halima", "El Fahs", "Djebel Oust", "Nadhour", "Zriba"};

    regionPicker.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent evt) {
        String selectedRegion = regionPicker.getSelectedString();
        if (selectedRegion.equals("Ariana")) {
            villePicker.setStrings(ArianaVilles);
        } else if (selectedRegion.equals("Béja")) {
            villePicker.setStrings(BéjaVilles);
        } else if (selectedRegion.equals("Ben Arous")) {
            villePicker.setStrings(BenArousVilles);
        }else if (selectedRegion.equals("Bizerte")) {
            villePicker.setStrings(BizerteVilles);
        
        }else if (selectedRegion.equals("Gabès")) {
            villePicker.setStrings(GabèsVilles);
        
        }else if (selectedRegion.equals("Gafsa")) {
            villePicker.setStrings(GafsaVilles);
        
        }else if (selectedRegion.equals("Jendouba")) {
            villePicker.setStrings(JendoubaVilles);
        
        }else if (selectedRegion.equals("Kairouan")) {
            villePicker.setStrings(KairouanVilles);
        
        }else if (selectedRegion.equals("Kasserine")) {
            villePicker.setStrings(KasserineVilles);
        
        }else if (selectedRegion.equals("Kébili")) {
            villePicker.setStrings(KébiliVilles);
        
        }else if (selectedRegion.equals("Kef")) {
            villePicker.setStrings(BenArousVilles);
        
        }else if (selectedRegion.equals("Mahdia")) {
            villePicker.setStrings(KefVilles);
        
        }else if (selectedRegion.equals("Manouba")) {
            villePicker.setStrings(ManoubaVilles);
        
        }else if (selectedRegion.equals("Médenine")) {
            villePicker.setStrings(MédenineVilles);
        
        }else if (selectedRegion.equals("Monastir")) {
            villePicker.setStrings(MonastirVilles);
        
        }else if (selectedRegion.equals("Nabeul")) {
            villePicker.setStrings(NabeulVilles);
        
        }else if (selectedRegion.equals("Sfax")) {
            villePicker.setStrings(SfaxVilles);
        
        }else if (selectedRegion.equals("Sidi Bouzid")) {
            villePicker.setStrings(SidibouzidVilles);
        
        }else if (selectedRegion.equals("Siliana")) {
            villePicker.setStrings(SilianaVilles);
        
        }else if (selectedRegion.equals("Sousse")) {
            villePicker.setStrings(SousseVilles);
        
        }else if (selectedRegion.equals("Tataouine")) {
            villePicker.setStrings(TataouineVilles);
        
        }else if (selectedRegion.equals("Tozeur")) {
            villePicker.setStrings(TozeurVilles);
        
        }else if (selectedRegion.equals("Tunis")) {
            villePicker.setStrings(tunisVilles);
        
        }else if (selectedRegion.equals("Zaghouan")) {
            villePicker.setStrings(ZaghouenVilles);
        
        }
    }
});
        TextField tfU =  new TextField("","Rue");
        TextField tfC =  new TextField("","Code postal");
        
    
        
        Container c = new Container(BoxLayout.x());

       

        
        Button btnValider = new Button("Valider");    
        
        f.add(tfPrenom);
        f.add(tfNom);
        f.add(tfNum);
        f.add(regionPicker);
        f.add(villePicker);
        f.add(tfU);
        f.add(tfC);
        
        f.add(c);

        f.add(btnValider);
        
        f.show();
        
        btnValider.addActionListener(new ActionListener() {

          @Override
          public void actionPerformed(ActionEvent evt) {
         Form f2 = new Form(BoxLayout.y());
         
         Label lPrenom = new Label("Prenom : "+ tfPrenom.getText());
         Label lNom = new Label("Nom : "+ tfNom.getText());
         Label lNum = new Label("Num : "+ tfNum.getText());
         Label lR = new Label("Region : "+ regionPicker.getSelectedString());
         Label lv = new Label("Ville : "+ villePicker.getSelectedString());
         Label lU = new Label("Rue : "+ tfU.getText());
         Label lC = new Label("Code postal : "+ tfC.getText());

         
         f2.add(lPrenom);
         f2.add(lNom);
         f2.add(lNum);
         f2.add(lR);
         f2.add(lv);
         f2.add(lU);
         f2.add(lC);

         f2.show();
         
          }
      });
        
        
        
        
        
                
      
      
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
